# Generated by Django 5.1.4 on 2025-01-14 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('voter_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('permanent_address', models.CharField(max_length=255)),
                ('temporary_address', models.CharField(blank=True, max_length=255, null=True)),
                ('age', models.PositiveIntegerField()),
                ('dob', models.DateField()),
                ('voter_image', models.ImageField(blank=True, null=True, upload_to='voter_images/')),
                ('blood_group', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
    ]
